---
- name: install Python 3.6
  yum:
    name:
      - python36
      - python36-pip
      - python36-setuptools
    state: installed

- name: install common tools
  pip:
    name:
      - PyYAML
    virtualenv: /opt/cloud_sdk
    virtualenv_command: /bin/python3 -m venv

- name: create citc config dir
  file:
    path: /etc/citc
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: copy mgmt_shape.yaml
  copy:
    src: /home/opc/mgmt_shape.yaml
    dest: /etc/citc/mgmt_shape.yaml
    owner: slurm
    group: slurm
    mode: 0744
  when: '"/home/opc/mgmt_shape.yaml" is exists'

- name: copy shapes.yaml
  copy:
    src: /tmp/shapes.yaml
    dest: /etc/citc/shapes.yaml
    owner: slurm
    group: slurm
    mode: 0744

- name: copy startnode.yaml
  copy:
    src: /tmp/startnode.yaml
    dest: /etc/citc/startnode.yaml
    owner: slurm
    group: slurm
    mode: 0744

- name: configure startnode script
  copy:
    src: startnode.py
    dest: /usr/local/bin/startnode
    mode: 0755

- name: configure stopnode script
  copy:
    src: stopnode.py
    dest: /usr/local/bin/stopnode
    mode: 0755

- name: configure update_config script
  template:
    src: update_config.j2
    dest: /usr/local/bin/update_config
    mode: 0755

# TODO Replace this with openssh_keypair when we use Ansible 2.8
- name: generate SSH host keys for compute nodespace
  shell: ssh-keygen -t {{ item.type }} -b {{ item.size }} -f {{ item.path }} -N "" < /dev/null
  args:
    creates: "{{ item.path }}"
  with_items:
    - {"type": "ed25519", "size": 4096, "path": "/home/slurm/ssh_host_ed25519_key"}
    - {"type": "rsa", "size": 4096, "path": "/home/slurm/ssh_host_rsa_key"}
    - {"type": "ecdsa", "size": 521, "path": "/home/slurm/ssh_host_ecdsa_key"}

- name: set ownership of host files
  file:
    path: "{{ item }}"
    owner: slurm
    group: slurm
  loop:
    - /home/slurm/ssh_host_ed25519_key
    - /home/slurm/ssh_host_ed25519_key.pub
    - /home/slurm/ssh_host_rsa_key
    - /home/slurm/ssh_host_rsa_key.pub
    - /home/slurm/ssh_host_ecdsa_key
    - /home/slurm/ssh_host_ecdsa_key.pub

- name: load the startnode config
  include_vars:
    file: /etc/citc/startnode.yaml
    name: startnode_config

- name: create cloud-init bootstrap script
  copy:
    content: |
      #! /bin/bash

      date

      cat > /etc/ssh/ssh_host_ecdsa_key << EOF
      {{ lookup('file', '/home/slurm/ssh_host_ecdsa_key') }}
      EOF
      cat > /etc/ssh/ssh_host_ecdsa_key.pub << EOF
      {{ lookup('file', '/home/slurm/ssh_host_ecdsa_key.pub') }}
      EOF
      cat > /etc/ssh/ssh_host_rsa_key << EOF
      {{ lookup('file', '/home/slurm/ssh_host_rsa_key') }}
      EOF
      cat > /etc/ssh/ssh_host_rsa_key.pub << EOF
      {{ lookup('file', '/home/slurm/ssh_host_rsa_key.pub') }}
      EOF
      cat > /etc/ssh/ssh_host_ed25519_key << EOF
      {{ lookup('file', '/home/slurm/ssh_host_ed25519_key') }}
      EOF
      cat > /etc/ssh/ssh_host_ed25519_key.pub << EOF
      {{ lookup('file', '/home/slurm/ssh_host_ed25519_key.pub') }}
      EOF
      chmod 600 /etc/ssh/ssh_host_*
      chmod 644 /etc/ssh/ssh_host_*.pub

      # Put the admin ssh keys somewhere that can be found
      cat > /root/citc_authorized_keys << EOF
      {{ lookup('file', '/home/citc/.ssh/authorized_keys') }}
      EOF

      {% if ansible_local.citc.csp == "aws" %}
      yum install -y epel-release
      yum install -y jq awscli
      region=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output '.region')
      instanceid=$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)
      name=$(aws ec2 describe-tags --region=${region} --filters "Name=resource-id,Values=${instanceid}" --output text --query 'Tags[?Key==`Name`].Value')
      hostnamectl set-hostname ${name}
      {% endif %}

      yum install -y ansible git
      cat > /root/hosts <<EOF
      [compute]
      $(hostname -f)
      EOF
      mkdir /etc/ansible/facts.d/
      cat > /etc/ansible/facts.d/citc.fact <<EOF
      {"csp":"{{ ansible_local.citc.csp }}", "fileserver_ip":"{{ ansible_local.citc.fileserver_ip }}"}
      EOF
      python -u /usr/bin/ansible-pull --url={{ ansible_pull_repo }} \
        --checkout={{ startnode_config.ansible_branch }} \
        --inventory=/root/hosts {{ bootstrap_ansible_pull_playbook }} >> /root/ansible-pull.log

      date
    dest: /home/slurm/bootstrap.sh
    owner: slurm

- name: copy list_nodes script
  copy:
    src: list_nodes.sh
    dest: /usr/local/bin/list_nodes
    mode: 0755
