---
- name: install MySQL-python
  yum: name=MySQL-python state=present

- name: install mariadb
  yum:
    name: mariadb-server
    state: installed

- name: start service mariadb
  service:
    name: mysqld
    state: started
    enabled: yes

- name: add auth option
  shell: echo "default-authentication-plugin=mysql_native_password" >> /etc/my.cnf

- name: create slurm accounting database
  mysql_db:
    name: slurmacct
    state: present

- name: create slurm MySQL user
  mysql_user:
    name: slurm
    password: "{{ slurm_accounting_db_password }}"
    priv: 'slurmacct.*:ALL'
    state: present
